Repository coliff/bootstrap-ie8, pull requests merged in 2018-05, with the labels that each got.

#35 display buttons fix
  css/bootstrap-ie8.css
  css/bootstrap-ie9.css
Labels: bug, enhancement

#31 javascript file for missing functions on ie8
  js/bootstrap-ie8.js
Labels: enhancement, javascript

#39 update JS versions
  README.md
  test.htm
Labels: enhancement

#44 Add package.json
  package.json
Labels: enhancement

#47 Recommended vscode prefs
  .vscode/extensions.json
  .vscode/settings.json
Labels: enhancement

#52 SVG images with .img-fluid are disproportionately sized on IE9
  css/bootstrap-ie9.css
Labels: ie9
